name = "todo-journal-dev"
type = "javascript"
account_id = "bd5d47aef41fb2139f547a3349f5716f"
zone_id = "72fdb6a1e6c368d54f90b78bff6f58da"
workers_dev = true
route = "develop.todojournal.com/*"
vars = { ENVIRONMENT = "dev" }

[env.staging]
name = "todo-journal-staging"
vars = { ENVIRONMENT = "staging" }
route = "staging.todojournal.com/*"
workers_dev = true

[env.production]
name = "todo-journal"
vars = { ENVIRONMENT = "production" }
route = "todojournal.com/*"
workers_dev = true
